# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: true

future:      true

markdown: redcarpet
redcarpet:
  extensions: ["strikethrough", "lax_spacing"]

# Setup
title:               SAMWAS
tagline:             On the Line
url:                 http://jeffreylarrimore.com/samwas/
paginate:            5
baseurl:             "/samwas/"
host: 0.0.0.0

# Assets
#
# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir:          _sass
  style:            :compressed

# About/contact
name:              Jeffrey Larrimore
url:               https://twitter.com/okayjeffrey
email:             me@jeffreylarrimore.com
